### ISSUE TITLE
Use jayq as jQuery in external libraries

### ISSUE THREAD

**Issue by CodeTaha** [ibdknox/jayq#61]
I am using [https://datatables.net](url) which has a dependency of jQuery which ofcourse I want to avoid as I am using Reagent. I am including the library in my project through :foreign-libs. I get an error saying jQuery is not defined from the dataTables.js, which is due to the library using jQuery instead of $ and being called before jayq. 
Do you have an idea of a workaround this problem? It would be amazing if this can be achieved and jquery can be removed completely.

**Comment by zachcurry** [comment]
Hi @CodeTaha ! :wave:

jayq is not a standalone replacement for JQuery. It's a wrapper for using JQuery (indirectly) in Clojurescript applications. jayq depends on JQuery. If jayq is working in your project, you must have JQuery already, otherwise jayq wouldn't work, and your problem is probably that your external library, datatables, is loaded before JQuery, hence the error.

Also, you can use JQuery and Reagent so long as you are careful not to use both to manipulate the same DOM nodes as it can lead to some gnarly bugs.

**Comment by frankhale** [comment]
I second what @zachcurry said. I'm going to close this issue but if there are any questions or room for discussion in using DataTables with Reagent (will also need a bit of jayq thrown in). We can certainly have that discussion. I wrote a React component that I've been using for over a year (it's in JS though) that allows for easy use of DataTables in a React application. If there is interest I could try a port to Clojurescript if need be or simply put that up on my Github if people are interested in trying a port themselves. All in all it's pretty easy to use DataTables from React apps.

**Comment by CodeTaha** [comment]
Thanks, I was able to resolve it by directly using jQuery. Unfortunately datatables was not happy using jayQ
